chore: add option to update pods in rolling updates (#1789)
Closes:
[221](https://github.com/appsmithorg/cloud-deployment/issues/221)
Currently, when a user install appsmith-ee with HA. We give update
rolling update with the following style.
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

With this change we can give users the flexibility to configure how many
pods have to come up/down on an update.

**Imago has nothing to do with imagePullPolicy:**

```
root@ip-172-31-2-224:~/gp# docker exec -it -u root 27ccbef0968d sh
# mkdir temptest && cd $_
# touch temptest.txt temptest2.txt
# ls
temptest.txt  temptest2.txt
# pwd
/temptest
# cd ..
# ls temptests/
ls: cannot access 'temptests/': No such file or directory
# ls temptest
temptest.txt  temptest2.txt
#
root@ip-172-31-2-224:~/gp# docker commit 27ccbef0968d gouthamappsmith/nginx-amd64
sha256:e10898f8925ef3aece5a07e509a10aab70350a5e5d0113a20c978e49336d3d46
root@ip-172-31-2-224:~/gp# docker push gouthamappsmith/nginx-amd64
Using default tag: latest
The push refers to repository [docker.io/gouthamappsmith/nginx-amd64]
c1df73cf5aae: Pushed
b9270fabeb18: Layer already exists
f62590d48fe5: Layer already exists
0b27f1638f81: Layer already exists
629fd7b81c65: Layer already exists
e543857b2aef: Layer already exists
6310117db5a7: Layer already exists
4b3ba104e9a8: Layer already exists
latest: digest: sha256:c94879fb171ec9125c411f6fdd83377a9367528111cf163633fe52f83ac58d92 size: 1984
root@ip-172-31-2-224:~/gp#
logout
ubuntu@ip-172-31-2-224:/var/snap/amazon-ssm-agent/6563$
exit


Exiting session with sessionId: goutham@appsmith.com-02e16347dd69d90ff.

(hackathon) ➜  hackathon kubectl get deployments nginx-deployment -o yaml | grep -i image
    imago-config-spec: '{"containers":[{"name":"nginx","image":"gouthamappsmith/nginx-amd64"}],"initContainers":[]}'
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"gouthamappsmith/nginx-amd64","imagePullPolicy":"IfNotPresent","name":"nginx","ports":[{"containerPort":80,"name":"http-web-svc"}]}]}}}}
      - image: gouthamappsmith/nginx-amd64@sha256:6a6be949ab6953146f4e0060defba9275e05080c657322c59528bf8f0fec335c
        imagePullPolicy: IfNotPresent
(hackathon) ➜  hackathon kubectl exec -it -u root nginx-deployment-5df7b64774-pjw9t sh
error: unknown shorthand flag: 'u' in -u
See 'kubectl exec --help' for usage.
(hackathon) ➜  hackathon kubectl exec -it nginx-deployment-5df7b64774-pjw9t sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
# ls
bin  boot  dev	docker-entrypoint.d  docker-entrypoint.sh  etc	home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  temp  tmp  usr  var
# ls temptest
ls: cannot access 'temptest': No such file or directory
#
command terminated with exit code 2
(hackathon) ➜  hackathon kubectl create job --from=cronjob/imago imago-manual-001
job.batch/imago-manual-001 created
(hackathon) ➜  hackathon kubectl logs imago-manual-001-z62tt
2023/07/24 10:33:04 checking default/Deployment/appsmith
2023/07/24 10:33:06     appsmith ok
2023/07/24 10:33:06 checking default/Deployment/cloudservice
2023/07/24 10:33:08     cloudservice ok
2023/07/24 10:33:08 checking default/Deployment/ksm-kube-state-metrics
2023/07/24 10:33:09     kube-state-metrics ok
2023/07/24 10:33:09 checking default/Deployment/maildev
2023/07/24 10:33:12     maildev ok
2023/07/24 10:33:12 checking default/Deployment/nginx-deployment
2023/07/24 10:33:14     nginx need to be updated from gouthamappsmith/nginx-amd64@sha256:6a6be949ab6953146f4e0060defba9275e05080c657322c59528bf8f0fec335c to gouthamappsmith/nginx-amd64@sha256:c94879fb171ec9125c411f6fdd83377a9367528111cf163633fe52f83ac58d92
2023/07/24 10:33:14 update default/Deployment/nginx-deployment
2023/07/24 10:33:14 checking default/DaemonSet/logdna-agent
2023/07/24 10:33:16     logdna-agent ok
2023/07/24 10:33:16 checking default/DaemonSet/prom-node-prometheus-node-exporter
2023/07/24 10:33:19     node-exporter ok
2023/07/24 10:33:19 checking default/StatefulSet/grafana-agent
(hackathon) ➜  hackathon kubectl exec -it nginx-deployment-6d49d49878-r7jlw sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
# ls temptest
temptest.txt  temptest2.txt
#

```