fix: remove noCursorTimeout from workspace query (#1324)
## Description
> Mongo atlas Free tier and shared clusters can't use the noTimeout
cursor option as mentioned in the documentation
[here](https://www.mongodb.com/docs/atlas/reference/free-shared-limitations/#operational-limitations)

> `noCursorTimeout` is failing in the latest Atlas Free tier with the
error below because it's not supported for a selected clusters.
```
Error in mongock process. ABORTED MIGRATION
io.mongock.api.exception.MongockException: Error in method[Migration103EeAddInviteUsersApplicationPolicyToApplicationPolicies.addInviteUsersApplicationPolicyToApplicationPolicy] : Command failed with error 8000 (AtlasError): 'noTimeout cursors are disallowed in this atlas tier' on server test1-shard-00-02.xsfdf.mongodb.net:27017. The full response is {"ok": 0, "errmsg": "noTimeout cursors are disallowed in this atlas tier", "code": 8000, "codeName": "AtlasError"}
```

Fixes # (issue)
> if no issue exists, please create an issue and ask the maintainers
about this first


Media
> A video or a GIF is preferred. when using Loom, don’t embed because it
looks like it’s a GIF. instead, just link to the video


## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?
> Not yet tested.

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking
(copy link from comments dropped on this PR)


## Checklist:
### Dev activity
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] PR is being merged under a feature flag


### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or
manual QA
- [ ] Organized project review call with relevant stakeholders after
Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

---------

Co-authored-by: Nilesh Sarupriya <20905988+nsarupr@users.noreply.github.com>